### ISSUE TITLE
 Do you have plans to support .NET 8?

### ISSUE THREAD

**Issue by honeyhead** [YBTopaz8/Chat-App-.NET-MAUI-LIVE-QUERY#1]
I’m the person who commented on your YouTube video. I really enjoyed watching your content—it’s fascinating! I’ve experimented with various tools like Ably and SignalR, but I’ve faced challenges in building an efficient and fast chat server while keeping costs low.

I also tried Supabase Realtime, but the time it takes to establish a socket connection was too long.

Because of these reasons, I became interested in trying Parse Server along with your library. However, I think upgrading to version 9 for a live service at this point poses significant risks. That’s why I hope it could work on .NET 8 as well. What do you think?

**Comment by honeyhead** [comment]
Live Query Source target is .NET 9, and I understand it supports versions 5, 6, 7, and 8 as well. Are there any significant issues we should be aware of?

**Comment by YBTopaz8** [comment]
Hi!
Thank you!
I hope you find it simple and useful !
Ideally .NET 8 (and MAUI as well) should be supported too!
I just tested it once again and pushed a commit right now where I downgraded the demo project to .NET 8 just to test.

Still working good!
Are you facing any specific issues perhaps? (let me know)

#### By the way I have a pretty big Wiki [Here](https://github.com/YBTopaz8/Parse-LiveQueries-DOTNET/wiki)
![image](https://github.com/user-attachments/assets/eca30b0f-b314-4f99-90d8-e31299979e3b)

**Comment by honeyhead** [comment]
Oh, thanks! I didn’t realize there was a wiki. I just saw it now.
I was just following along with the videos so far, and there haven’t been any issues yet.
But I was worried that there would be a problem if it wasn't NET9

These are really things I need, so thank you for working on them.
I’ll share my progress if I achieve anything!

**Comment by YBTopaz8** [comment]
So far I haven't had any report with .NET compatibilities (but I keep an eye out!)
You can confidently launch them on any .net platform from .NET 5 till ... 9!
Unity should work too since MAUI works great.
I'll do another video explaining the WIKI too. Might come in some weeks!
